### ISSUE TITLE
Error: ETIMEDOUT

### ISSUE THREAD

**Issue by CKMartens** [Mic-M/iobroker.fully-kiosk-browser-script#1]
Ich habe das Script heute aktiviert und leider kommt bei mir folgender Fehler

`cript.js.Vis.Steuerung_Fully-Browser: Fully Browser: Folgender Fehler bei http-Request aufgetreten: Error: ETIMEDOUT`

**Comment by Mic-M** [comment]
Danke für Dein Feedback.
Kommt der Fehler im Log alle 2 Minuten oder nur unregelmäßig? Haben sich die Datenpunkte unter "javascript.0.mic.FullyBrowser.Info" ansonsten aktualisiert?
Falls nur unregelmäßig: Kann schon mal sein, dass das Tablet mal nicht erreichbar ist, passiert bei mir auch sehr unregelmäßig, also 1-2mal am Tag.

**Comment by CKMartens** [comment]
Hi, der kommt alle 2 Minuten.

Ich habe gerade nochmal V0.2 getestet, da ist der Fehler nicht.

**Comment by Mic-M** [comment]
Interessant. Gleiche Einstellungen, also IP und Port?

**Comment by CKMartens** [comment]
Ja, alles gleich....

**Comment by Mic-M** [comment]
Echt seltsam, kann ich im Moment nicht nachstellen, zumal sich von v0.2 auf v0.3 nicht wirklich die Abfrage selbst geändert hat, die diesen ETIMEDOUT verursachen würde.

**Comment by Chaot1** [comment]
Der Fehler kam bei mir als das Tablet vom WLan getrennt war.
Könnte sein das der Fehler auch ausgelöst wird wenn das Tablet im Screensafer ist und dabei das WLan abschaltet. Das war bei mir zumindest in der Anfangszeit so.
Einzustellen unter Fully.

**Comment by CKMartens** [comment]
Ich werde das heute Abend mal testen ob es damit zu tun hat

**Comment by CKMartens** [comment]
Ok, es ist tatsächlich so, das das Samsung Tab sobald der Screensaver an geht, das WLAN abschaltet.

Mein billig Medion Tablett hatte diese Eigenart nicht. Danke für eure Geduld.

Der Issue kann geschlossen werden.

**Comment by Chaot1** [comment]
Das kannst du im Fully einstellen.
Unter dem Punkt
Power Settings - Set WiFi Wakelock. Damit dürfte das Problem behoben sein.

**Comment by CKMartens** [comment]
Entschuldigung, zu früh gefreut...

Ich habe Wakelock schon eingeschaltet gehabt und habe jetzt wieder die Version 0.3 eingespielt. Und prompt kommt der Fehler wieder. Danach habe ich die Version 0.2 wieder eingespielt und nun kommt auch hier der Fehler...

Nun verstehe ich gar nichts mehr
